alerting:
  github:
    token: "<github-token>" # WARN: DO NOT CHANGE THIS LINE
    owner: project-sony
    repository: devops-jatim-25

endpoints:
  - name: Leantime
    url: <leantime-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: github
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        title: "⚠️ Alert - Leantime is down"
        description: |
          Gatus detected an issue with Leantime:
          - Status: {{STATUS}}
          - Condition: {{CONDITION}}
          - Timestamp: {{TIMESTAMP}}

  - name: Gatus
    url: <gatus-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
    alerts:
      - type: github
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        title: "⚠️ Alert - Gatus is down"
        description: |
          Gatus detected an issue with Gatus:
          - Status: {{STATUS}}
          - Condition: {{CONDITION}}
          - Timestamp: {{TIMESTAMP}}